#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 07 12:50:38 CST 2026
maven-metadata-alimaven.xml.lastUpdated=1778129438943
maven-metadata-ossrh.xml.error=
maven-metadata-ossrh.xml.lastUpdated=1778129438943
