-- kb_document 知识文档表
CREATE TABLE IF NOT EXISTS kb_document (
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键（雪花ID）',
    title VARCHAR(512) NOT NULL COMMENT '文档标题',
    category_id BIGINT NULL COMMENT '分类ID',
    kb_id BIGINT NULL COMMENT '所属知识库ID（为空时使用默认Milvus集合）',
    owner_id BIGINT NOT NULL COMMENT '上传者用户ID',
    department_id BIGINT NULL COMMENT '所属部门ID',
    file_name VARCHAR(512) NULL COMMENT '原始文件名',
    file_url VARCHAR(1024) NULL COMMENT '文件存储路径',
    file_type VARCHAR(128) NULL COMMENT 'MIME类型（Tika探测后覆盖）',
    file_size BIGINT NULL COMMENT '文件大小（字节）',
    summary VARCHAR(1024) NULL COMMENT '摘要（分块后取前200字）',
    content_text LONGTEXT NULL COMMENT 'Tika解析后的完整正文',
    tags VARCHAR(512) NULL COMMENT '标签（逗号分隔）',
    permission_type VARCHAR(64) NOT NULL COMMENT '权限类型 ALL/DEPARTMENT/PROJECT/USER/ADMIN',
    status VARCHAR(64) NOT NULL COMMENT '文档状态 PENDING/RUNNING/SUCCESS/FAILED等',
    current_version INT DEFAULT 1 COMMENT '当前版本号',
    chunk_count INT DEFAULT 0 COMMENT '切片数量（查询计数）',
    enabled INT DEFAULT 1 COMMENT '是否启用 0-禁用 1-启用',
    process_mode VARCHAR(32) DEFAULT 'CHUNK' COMMENT '处理模式 CHUNK/PIPELINE',
    chunk_strategy VARCHAR(64) NULL COMMENT '分块策略 FIXED_SIZE/PARAGRAPH',
    chunk_config LONGTEXT NULL COMMENT '分块参数JSON',
    pipeline_id VARCHAR(128) NULL COMMENT 'Pipeline定义ID（PIPELINE模式使用）',
    source_type VARCHAR(32) DEFAULT 'FILE' COMMENT '来源类型 FILE/URL',
    source_location VARCHAR(1024) NULL COMMENT 'URL来源地址',
    schedule_enabled INT DEFAULT 0 COMMENT '定时拉取开关 0-关闭 1-开启',
    schedule_cron VARCHAR(128) NULL COMMENT '定时Cron表达式',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    KEY idx_kb_document_owner (owner_id),
    KEY idx_kb_document_category (category_id),
    KEY idx_kb_document_kb (kb_id),
    KEY idx_kb_document_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识文档表';
