#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 07 12:51:32 CST 2026
maven-metadata-apache.snapshots.xml.lastUpdated=1778129492546
maven-metadata-alimaven.xml.lastUpdated=1778129492546
maven-metadata-apache.snapshots.xml.error=
