#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri May 08 14:11:28 CST 2026
maven-metadata-apache.snapshots.xml.lastUpdated=1778220688649
maven-metadata-alimaven.xml.lastUpdated=1778220688648
maven-metadata-apache.snapshots.xml.error=
