#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri May 08 14:11:29 CST 2026
maven-metadata-apache.snapshots.xml.lastUpdated=1778220689925
maven-metadata-alimaven.xml.lastUpdated=1778220689924
maven-metadata-apache.snapshots.xml.error=
