spring:
  config:
    import: optional:classpath:application-secrets.yml
  application:
    name: enterprise-collaboration-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        fail-fast: false
        shared-configs:
          - data-id: common-config.yaml
            group: DEFAULT_GROUP
            refresh: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

server:
  port: 8090

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

auth:
  jwt:
    expiration: 86400000
