-- 改造 sys_doc 表
ALTER TABLE sys_doc
  ADD COLUMN version INT NOT NULL DEFAULT 0 COMMENT '当前操作版本号',
  ADD COLUMN snapshot_version INT NOT NULL DEFAULT 0 COMMENT '最后快照版本号',
  ADD COLUMN created_by BIGINT DEFAULT NULL COMMENT '创建者';

-- 操作日志表
CREATE TABLE IF NOT EXISTS sys_doc_operation (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  doc_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  version INT NOT NULL,
  operation LONGTEXT NOT NULL COMMENT 'Quill Delta JSON',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_doc_version (doc_id, version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 评论表
CREATE TABLE IF NOT EXISTS sys_doc_comment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  doc_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  anchor_index INT DEFAULT NULL COMMENT '锚定起始位置',
  anchor_length INT DEFAULT NULL COMMENT '锚定长度',
  parent_id BIGINT DEFAULT NULL COMMENT '回复目标评论ID',
  resolved TINYINT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_doc_comment (doc_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 分享链接表
CREATE TABLE IF NOT EXISTS sys_doc_share_link (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  doc_id BIGINT NOT NULL,
  token VARCHAR(64) NOT NULL,
  permission VARCHAR(10) NOT NULL COMMENT 'VIEW/COMMENT/EDIT',
  expired_at DATETIME DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX idx_token (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 协作者表
CREATE TABLE IF NOT EXISTS sys_doc_collaborator (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  doc_id BIGINT NOT NULL,
  target_type VARCHAR(10) NOT NULL COMMENT 'USER/DEPT',
  target_id BIGINT NOT NULL,
  permission VARCHAR(10) NOT NULL COMMENT 'VIEW/COMMENT/EDIT',
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_doc_collaborator (doc_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
