CREATE TABLE IF NOT EXISTS kb_intent_node (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    parent_id BIGINT NULL COMMENT '父节点ID，NULL为根场景',
    name VARCHAR(128) NOT NULL COMMENT '节点名称',
    level TINYINT NOT NULL DEFAULT 1 COMMENT '层级 1=场景 2=意图',
    sort_order INT DEFAULT 0 COMMENT '同级排序',
    description VARCHAR(512) NULL COMMENT '节点说明',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_intent_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='意图节点表';

CREATE TABLE IF NOT EXISTS kb_intent_rule (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    node_id BIGINT NOT NULL COMMENT '意图节点ID',
    rule_type VARCHAR(16) NOT NULL COMMENT 'keyword / regex',
    expression VARCHAR(256) NOT NULL COMMENT '关键词或正则表达式',
    weight DOUBLE NOT NULL DEFAULT 1.0 COMMENT '匹配权重',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_rule_node (node_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='意图匹配规则表';

CREATE TABLE IF NOT EXISTS kb_intent_kb_rel (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    node_id BIGINT NOT NULL COMMENT '意图节点ID',
    kb_id BIGINT NOT NULL COMMENT '知识库ID',
    weight DOUBLE NOT NULL DEFAULT 1.0 COMMENT '检索权重',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_intent_kb (node_id, kb_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='意图知识库关联表';
