CREATE TABLE IF NOT EXISTS kb_keyword_mapping (
    id          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    keyword     VARCHAR(100) NOT NULL,
    kb_name     VARCHAR(100) NOT NULL,
    priority    INT          NOT NULL DEFAULT 0,
    strategy    VARCHAR(255) DEFAULT NULL,
    enabled     TINYINT(1)   NOT NULL DEFAULT 1,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
