spring:
  config:
    import: optional:classpath:application-secrets.yml
  application.name: enterprise-workbench-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/enterprise_collaboration?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

server.port: 8084

mybatis-plus.configuration.map-underscore-to-camel-case: true

knowledge.service.url: http://localhost:8083
