spring:
  config:
    import: optional:classpath:application-secrets.yml
  application:
    name: enterprise-workbench-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        fail-fast: false
        shared-configs:
          - data-id: common-config.yaml
            group: DEFAULT_GROUP
            refresh: true

server:
  port: 8084

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
